# Generated by Django 6.0.6 on 2026-07-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('課題', '課題'), ('アルバイト', 'アルバイト'), ('サークル', 'サークル'), ('プライベート', 'プライベート')], default='課題', max_length=20),
        ),
    ]
